name: Build and Push image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v4

    - name: setup Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Check DockerHub Username
      run: echo "Username is ${{ secrets.DOCKERHUB_USERNAME }}"


    - name: login Dockerhub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: build and push image
      uses: docker/build-push-action@v5
      with:
         context: .
         file: ./Dockerfile
         push: true
         tags: owen2chw/2025cloud:$(date +'%Y%m%d-%H%M%S')
        
